### ISSUE TITLE
A calling convention for threaded code in Mit without global variables

### ISSUE THREAD

**Issue by apt1002** [rrthomas/pforth#25]
Copied from an email as requested (with an insignificant change to RET).

I've been thinking about threaded pForth. As I recall, you have two global variables: RSP and IP. I think you might have a third one too for the return address. I remember that a large fraction of the function prologue and epilogue is for manipulating these variables. I vaguely remember you saying that they are difficult to relocate. The accesses to the variables are difficult to optimise, because of aliasing.

I'd like to propose an alternative calling convention in which none of these global variables exists. Instead, the Forth IP is kept on top of the emulated return stack, and the Forth RSP is kept on top of the Mit stack. This eliminates most of the LIT instructions and solves the other problems too.

The interpreter loop:

```
interpreter_loop:
// Stack is ... RSP.
LIT_PC_REL(interpreter_loop) // Push the Mit return address.
LIT_1 DUP LIT(word_size) LOAD // Load IP from RSP.
LIT_0 DUP // IP
LIT(word_bytes) ADD // Increment IP.
LIT_3 DUP LIT(word_size) STORE // Save the new IP.
LIT(word_size) LOAD JUMP // Fetch an instruction and enter it.
```
The last line can be replaced with the following if you want your threaded code to be position-independent:
```
LIT_0 DUP LIT(word_size) LOAD ADD JUMP
```
The Forth ADD primitive:
```
ADD:
// Stack is ... x y RSP mit_return_address.
LIT_2 SWAP LIT_0 SWAP LIT_1 SWAP
// Stack is ... mit_return_address RSP x y.
ADD
LIT_1 SWAP JUMP
```
The Forth RET primitive:
```
RET:
// Stack is ... RSP mit_return_address.
// mit_return_address must be interpreter_loop.
POP
LIT(-word_bytes) ADD // Decrement RSP.
LIT_PC_REL(interpreter_loop) JUMP
```
The Forth CALL primitive:
```
CALL:
// Stack is ... to_call RSP mit_return_address
// mit_return_address must be interpreter_loop.
POP
LIT(word_bytes) ADD // Increment RSP.
LIT_0 SWAP
// Stack is ... RSP to_call
LIT_1 DUP LIT(word_size) STORE // Save the new IP.
LIT_PC_REL(interpreter_loop) JUMP
```
I can't quite remember the data structure that represents a word. Here I'm just going to assume that the Mit code at the entry point is immediately followed by the threaded code.
```
my_word:
// Stack is ... RSP mit_return_address
// mit_return_address must be interpreter_loop.
POP LIT_PC_REL(prologue) CALL // Does not return.
// Threaded code goes here.
```
The shared function prologue is similar to CALL above:
```
prologue:
// Stack is ... RSP to_call
LIT_0 SWAP
LIT(word_bytes) ADD // Increment RSP.
LIT_0 SWAP
// Stack is ... RSP to_call
LIT_1 DUP LIT(word_size) STORE // Save the new IP.
LIT_PC_REL(interpreter_loop) JUMP
```
The prologue can be placed immediately before interpreter_loop in order to avoid the last line.

**Comment by rrthomas** [comment]
Closing, as the mit-threaded back-end has been abandoned.
