### ISSUE TITLE
Fail to build from source on Mac OS X

### ISSUE THREAD

**Issue by abailly** [rrthomas/pforth#51]
I am trying to build `pforth` from source on Mac OS X (Monterey 12.2.1) and it fails at `./configure` step with:

```
 % ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for latexmk... /Library/TeX/texbin/latexmk
checking for grep that handles long lines and -e... /usr/bin/grep
checking for bee... /usr/local/bin/bee
checking for bee-as... no
configure: error: Could not find Bee as
```

I successfully installed bee v1.0 (https://github.com/rrthomas/bee/releases/tag/v1.0) but cannot install it from source (see https://github.com/rrthomas/bee/issues/18)

**Comment by abailly** [comment]
After fixing m4 version I was able to install the latest and greatest  `bee` but then now I have:
```
...
checking for bee... /usr/local/bin/bee
configure: error: /usr/local/bin/bee does not work!
```

This is odd 🤔

**Comment by rrthomas** [comment]
For pForth, bee version 1 is required (as documented in `README.md`).

The other problem you have is that the build system currently requires a Bee-capable fork of binutils (hence the failed search for Bee `as`). I will see if I can make this optional.

**Comment by rrthomas** [comment]
I have pushed a change to `configure.ac` that makes the use of binutils optional. Let me know if that fixes your problem, please!

**Comment by rrthomas** [comment]
Now passing on AppVeyor on macos, so closing this issue.

**Comment by abailly** [comment]
My bad, I did not check the version in the README :( After installing bee version 1.0, I was able to `./configure && make && make install`. Thanks for caring to look at this!
